package env

const (
	COMPANY_SERVER_PORT          = "COMPANY_SERVER_PORT"
	COMPANY_SERVER_READ_TIMEOUT  = "COMPANY_SERVER_READ_TIMEOUT"
	COMPANY_SERVER_WRITE_TIMEOUT = "COMPANY_SERVER_WRITE_TIMEOUT"
	COMPANY_CASSANDRA_HOST       = "COMPANY_CASSANDRA_HOST"
	COMPANY_CASSANDRA_KEYSPACE   = "COMPANY_CASSANDRA_KEYSPACE"
	COMPANY_JWT_SECRET_KEY       = "COMPANY_JWT_SECRET_KEY"
	COMPANY_JWT_EXPIRE_TIME      = "COMPANY_JWT_EXPIRE_TIME"
	COMPANY_BROKER_URL           = "COMPANY_BROKER_URL"
	COMPANY_BROKER_TOPIC         = "COMPANY_BROKER_TOPIC"
)
